version: "3.9"  # optional since v1.27.0
services:
  leads:
    build: .
    ports: 
      - 8080:8080
    environment:
       DB: mongodb://mongo:27017/cnv
       DATABASE_USER: postgres
       DATABASE_PASSWORD: 0M72k%10
       DATABASE_HOST: back-leads.c2tcvwezxaxn.us-east-1.rds.amazonaws.com
       DATABASE_PORT: 5432
       DATABASE_NAME: leads
       PORT: 8080
  database:
    image: postgres:13
    container_name: lead
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: lead
      APP_DB_NAME: lead
    ports:
      - 5431:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081  