version: "3.9"  # optional since v1.27.0
services:
  leads:
    build: .
    ports: 
      - 8080:8080
    environment:
       DATABASE_USER: postgres
       DATABASE_PASSWORD: 123
       DATABASE_HOST: localhost
       DATABASE_PORT: 5432
       DATABASE_NAME: lead
       PORT: 8080
  database:
    image: postgres:13
    container_name: lead
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: lead
      APP_DB_NAME: lead
    ports:
      - 5431:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081  